import { describe, expect, it } from "vitest";
import { base64UrlDecode, base64UrlEncode, encryptPayload } from "../../src/notify/web-push.js";

/**
 * RFC 8291 §5's worked example, verbatim.
 *
 * These are the published vectors and not a fixture generated by this code.
 * The distinction is the whole value of the test: encrypting and then
 * decrypting with our own implementation would prove only that it agrees
 * with itself, and every way this can go wrong — an `info` string off by a
 * byte, the two HKDF stages in the wrong order, the padding delimiter
 * omitted — produces something that round-trips through itself perfectly and
 * is rejected by every real push service.
 *
 * Values the RFC wraps across lines are joined here, and only joined; no
 * character has been re-cased, re-padded or otherwise "corrected".
 */
const VECTOR = {
  // The RFC gives the plaintext base64'd, as
  // `V2hlbiBJIGdyb3cgdXAsIEkgd2FudCB0byBiZSBhIHdhdGVybWVsb24`.
  plaintext: "When I grow up, I want to be a watermelon",
  salt: "DGv6ra1nlYgDCS1FRnbzlw",
  senderPrivateKey: "yfWPiYE-n46HLnH0KqZOF1fJJU3MYrct3AELtAQ-oRw",
  senderPublicKey:
    "BP4z9KsN6nGRTbVYI_c7VJSPQTBtkgcy27mlmlMoZIIgDll6e3vCYLocInmYWAmS6TlzAC8wEqKK6PBru3jl7A8",
  receiverPublicKey:
    "BCVxsr7N_eNgVRqvHtD0zTZsEc6-VV-JvLexhqUzORcxaOzi6-AYWXvTBHm4bjyPjs7Vd8pZGH6SRpkNtoIAiw4",
  authSecret: "BTBZMqHH6r4Tts7J_aSIgg",
  expected:
    "DGv6ra1nlYgDCS1FRnbzlwAAEABBBP4z9KsN6nGRTbVYI_c7VJSPQTBtkgcy27mlmlMoZIIgDll6e3vCYLocInmYWAmS6TlzAC8wEqKK6PBru3jl7A_yl95bQpu6cVPTpK4Mqgkf1CXztLVBSt2Ks3oZwbuwXPXLWyouBWLVWGNWQexSgSxsj_Qulcy4a-fN",
};

describe("RFC 8291 payload encryption", () => {
  it("reproduces the published ciphertext exactly", async () => {
    const localKeys = await importSenderKeys(VECTOR.senderPrivateKey, VECTOR.senderPublicKey);

    const encrypted = await encryptPayload(
      {
        endpoint: "https://push.example/receiver",
        p256dh: VECTOR.receiverPublicKey,
        auth: VECTOR.authSecret,
      },
      VECTOR.plaintext,
      { salt: base64UrlDecode(VECTOR.salt), localKeys },
    );

    expect(base64UrlEncode(encrypted)).toBe(VECTOR.expected);
  });

  it("puts the salt and the sender key in the header, where a receiver looks for them", async () => {
    // aes128gcm framing: salt(16) ‖ record size(4) ‖ key id length(1) ‖
    // sender public key(65) ‖ ciphertext. A receiver reads the sender's key
    // out of this header — there is nowhere else it could come from — so a
    // mis-sized header is not a cosmetic error, it is undecryptable.
    const encrypted = await encryptPayload(
      { endpoint: "https://push.example/receiver", p256dh: VECTOR.receiverPublicKey, auth: VECTOR.authSecret },
      "hello",
    );

    expect(encrypted.length).toBeGreaterThan(86);
    expect(encrypted[20]).toBe(65); // key id length: an uncompressed P-256 point
  });

  it("refuses a payload that would exceed the 4KB limit", async () => {
    // Every push service rejects an oversized payload, and the copy layer
    // asserts against this rather than discovering it in production.
    await expect(
      encryptPayload(
        { endpoint: "https://push.example/receiver", p256dh: VECTOR.receiverPublicKey, auth: VECTOR.authSecret },
        "x".repeat(4097),
      ),
    ).rejects.toThrow(/too large/i);
  });

  it("round-trips base64url without padding, including bytes that need the URL alphabet", async () => {
    // 0xfb/0xff are the byte pairs whose standard-alphabet encoding contains
    // `+` and `/`; if the substitution were dropped this is where it shows.
    const bytes = new Uint8Array([0x00, 0xfb, 0xff, 0xbe, 0x01]);
    expect(base64UrlEncode(bytes)).not.toMatch(/[+/=]/);
    expect(Array.from(base64UrlDecode(base64UrlEncode(bytes)))).toEqual(Array.from(bytes));
    // And decoding a real, unpadded vector gives the length the RFC states.
    expect(base64UrlDecode(VECTOR.salt).length).toBe(16);
    expect(base64UrlDecode(VECTOR.receiverPublicKey).length).toBe(65);
  });
});

async function importSenderKeys(privateKey: string, publicKey: string): Promise<CryptoKeyPair> {
  const raw = base64UrlDecode(publicKey);
  const jwk = {
    kty: "EC",
    crv: "P-256",
    d: privateKey,
    x: base64UrlEncode(raw.slice(1, 33)),
    y: base64UrlEncode(raw.slice(33, 65)),
    ext: true,
  };
  return {
    privateKey: await crypto.subtle.importKey("jwk", jwk, { name: "ECDH", namedCurve: "P-256" }, false, [
      "deriveBits",
    ]),
    publicKey: await crypto.subtle.importKey("raw", raw, { name: "ECDH", namedCurve: "P-256" }, true, []),
  };
}
