// scripts/build-icons.mjs
/**
 * Rasterises `src/views/icon.ts` into `src/views/icon-bytes.ts`.
 *
 * Run by hand (`node scripts/build-icons.mjs`) whenever the mark changes; its
 * output is **committed**, so CI never runs it and no rasteriser joins a
 * dependency list that has six entries in it.
 *
 * Bytes are emitted as base64 and decoded at module load. A Worker cannot
 * read a file from disk, and this project has no assets binding — see the
 * spec §5 for why adding one to serve three small files is the wrong trade.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ICON_SVG } from "../src/views/icon.ts";

const SIZES = [
  { size: 192, constant: "ICON_192_PNG" },
  { size: 512, constant: "ICON_512_PNG" },
  { size: 180, constant: "APPLE_TOUCH_ICON_PNG" },
];

try {
  execFileSync("rsvg-convert", ["--version"], { stdio: "ignore" });
} catch {
  console.error("rsvg-convert is not installed. On Arch: pacman -S librsvg");
  process.exit(1);
}

const dir = mkdtempSync(join(tmpdir(), "mtt-icons-"));
const svgPath = join(dir, "icon.svg");
writeFileSync(svgPath, ICON_SVG);

const emitted = SIZES.map(({ size, constant }) => {
  const out = join(dir, `icon-${size}.png`);
  execFileSync("rsvg-convert", ["-w", String(size), "-h", String(size), "-o", out, svgPath]);
  const base64 = readFileSync(out).toString("base64");
  return `/** ${size}×${size}, generated from ICON_SVG. */\nexport const ${constant} = decode(\n  "${base64}",\n);`;
});

writeFileSync(
  new URL("../src/views/icon-bytes.ts", import.meta.url),
  `// GENERATED BY scripts/build-icons.mjs — DO NOT EDIT BY HAND.
// Regenerate with: node scripts/build-icons.mjs
//
// The mark lives in src/views/icon.ts; this file is only its rasterised form,
// committed so that CI and deploys never need a rasteriser installed.

function decode(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

${emitted.join("\n\n")}
`,
);

console.log(`wrote src/views/icon-bytes.ts (${SIZES.map((s) => s.size).join(", ")})`);
